spring.datasource.url=jdbc:mysql://localhost:3306/homevalue
spring.datasource.username=root
spring.datasource.password=vISHAL_2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:1508}